#!/usr/bin/perl -w
use strict;
use warnings;
our $VERSION = '0.30';

use Kwiki;
Kwiki->new->load_hub->load_class('command')->process(@ARGV);

__END__

=head1 NAME

kwiki - The Kwiki Command Line Tool

=head1 USAGE

    > mkdir cgi-bin/my-kwiki
    > cd cgi-bin/my-kwiki
    > kwiki -install

    Kwiki software installed! Point your browser at this location.

=head1 DESCRIPTION

Kwiki is a simple extendable wiki framework, written in Perl.

=head1 AUTHOR

Brian Ingerson <INGY@cpan.org>

=head1 COPYRIGHT

Copyright (c) 2004. Brian Ingerson. All rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

See http://www.perl.com/perl/misc/Artistic.html

=cut

# vim: set ft=perl:
