name: Kwiki
version: 0.30
abstract: Kwiki Wiki Framework
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Spoon: 0.15
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
